// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickBite.Services.CouponAPI.Data;

#nullable disable

namespace QuickBite.Services.CouponAPI.Migrations
{
    [DbContext(typeof(CouponDBContext))]
    partial class CouponDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuickBite.Services.CouponAPI.Models.Coupon", b =>
                {
                    b.Property<int>("CouponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponID"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CouponID");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponID = 1,
                            CouponCode = "C120",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2025, 6, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DiscountAmount = 120.0,
                            IsActive = true,
                            MinAmount = 240,
                            UpdatedBy = 1,
                            UpdatedDate = new DateTime(2025, 6, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            CouponID = 2,
                            CouponCode = "C100",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2025, 6, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DiscountAmount = 100.0,
                            IsActive = true,
                            MinAmount = 200,
                            UpdatedBy = 1,
                            UpdatedDate = new DateTime(2025, 6, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            CouponID = 3,
                            CouponCode = "C75",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2025, 6, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DiscountAmount = 75.0,
                            IsActive = true,
                            MinAmount = 150,
                            UpdatedBy = 1,
                            UpdatedDate = new DateTime(2025, 6, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            CouponID = 4,
                            CouponCode = "C50",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2025, 6, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DiscountAmount = 50.0,
                            IsActive = true,
                            MinAmount = 100,
                            UpdatedBy = 1,
                            UpdatedDate = new DateTime(2025, 6, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            CouponID = 5,
                            CouponCode = "C25",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2025, 6, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DiscountAmount = 25.0,
                            IsActive = true,
                            MinAmount = 50,
                            UpdatedBy = 1,
                            UpdatedDate = new DateTime(2025, 6, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
